hwid: "admin-9234"
MONGO:
  HOST: "127.0.0.1"
  PORT: 27017
  AUTHENTICATION:
    ENABLED: false
    USERNAME: ""
    PASSWORD: ""
spawn:
  world: "world"
  x: 0
  y: 100
  z: 0
  yaw: 0
  pitch: 0
kit-edit:
  world: "world"
  x: 0
  y: 100
  z: 0
  yaw: 0
  pitch: 0
